language: generic
sudo: required
service:
    - docker
before_install:
    - docker build -t svvone/docker-test -f ./client/Dockerfile.dev ./client
script:
    - docker run -e CI=true svvone/docker-test npm run test
after_success:
    - docker build -f svvone/docker-nginx2 ./nginx2/Dockerfile ./nginx
    - docker build -f svvone/docker-client2 ./client/Dockerfile ./client
    - docker build -f svvone/docker-server2 ./client/Dockerfile ./server
    - docker build -f svvone/docker-worker2 ./client/Dockerfile ./worker
    - echo "$DOCKER_PASSWORD" | docker  login -u "$DOCKER_USERNAME" --password-stdin
    - docker push  svvone/docker-nginx2
    - docker push  svvone/docker-client2
    - docker push  svvone/docker-server2
    - docker push  svvone/docker-worker2