language: generic
sudo: required
service:
    - docker
before_install:
    - docker build -t svvone/docker-test -f ./client/Dockerfile.dev ./client
script:
    - docker run -e CI=true svvone/docker-test npm run test
